# rewritten for Synopsys tools by src/eval/sdc.py (time_scale=1000)
# generated by src/eval/sdc.py  top=verified_accu lib=asap7 period=0.5 ns  (config: constraints)
current_design verified_accu
create_clock -name clk -period 500 [get_ports clk]
set non_clk [snps_all_inputs_no_clocks]
set_input_delay 100 -clock clk $non_clk
set_output_delay 100 -clock clk [all_outputs]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R $non_clk
set_max_fanout 20 [current_design]
