/* Generated by Yosys 0.63 (git sha1 d3e297fcd, g++ 11.5.0-10ubuntu1~20~ppa3 -fPIC -O3) [the-openroad-project/yosys] */

module verified_accu(clk, rst_n, data_in, valid_in, valid_out, data_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [7:0] data_in;
  wire [7:0] data_in;
  input valid_in;
  wire valid_in;
  output valid_out;
  wire valid_out;
  output [9:0] data_out;
  wire [9:0] data_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire [31:0] _085_;
  wire [1:0] count;
  wire end_cnt;
  INV_X1 _086_ (
    .A(_028_),
    .ZN(_029_)
  );
  NAND2_X1 _087_ (
    .A1(data_in[3]),
    .A2(data_out[3]),
    .ZN(_030_)
  );
  NOR2_X1 _088_ (
    .A1(data_in[3]),
    .A2(data_out[3]),
    .ZN(_031_)
  );
  AND2_X1 _089_ (
    .A1(data_in[2]),
    .A2(data_out[2]),
    .ZN(_032_)
  );
  NAND2_X1 _090_ (
    .A1(data_in[1]),
    .A2(data_out[1]),
    .ZN(_033_)
  );
  NAND2_X1 _091_ (
    .A1(data_in[0]),
    .A2(data_out[0]),
    .ZN(_034_)
  );
  NOR2_X1 _092_ (
    .A1(data_in[1]),
    .A2(data_out[1]),
    .ZN(_035_)
  );
  XOR2_X1 _093_ (
    .A(data_in[1]),
    .B(data_out[1]),
    .Z(_036_)
  );
  OAI21_X1 _094_ (
    .A(_033_),
    .B1(_034_),
    .B2(_035_),
    .ZN(_037_)
  );
  OR2_X1 _095_ (
    .A1(data_in[2]),
    .A2(data_out[2]),
    .ZN(_038_)
  );
  XNOR2_X1 _096_ (
    .A(data_in[2]),
    .B(data_out[2]),
    .ZN(_039_)
  );
  AOI21_X1 _097_ (
    .A(_032_),
    .B1(_037_),
    .B2(_038_),
    .ZN(_040_)
  );
  AOI21_X1 _098_ (
    .A(_031_),
    .B1(_040_),
    .B2(_030_),
    .ZN(_041_)
  );
  AOI211_X1 _099_ (
    .A(_029_),
    .B(_031_),
    .C1(_040_),
    .C2(_030_),
    .ZN(_042_)
  );
  AOI21_X1 _100_ (
    .A(_042_),
    .B1(data_out[4]),
    .B2(data_in[4]),
    .ZN(_043_)
  );
  AOI221_X1 _101_ (
    .A(_042_),
    .B1(data_out[4]),
    .B2(data_in[4]),
    .C1(data_in[5]),
    .C2(data_out[5]),
    .ZN(_044_)
  );
  OR3_X1 _102_ (
    .A1(_026_),
    .A2(_027_),
    .A3(_044_),
    .ZN(_045_)
  );
  NAND2_X1 _103_ (
    .A1(_025_),
    .A2(_045_),
    .ZN(_046_)
  );
  NAND3_X1 _104_ (
    .A1(_024_),
    .A2(_025_),
    .A3(_045_),
    .ZN(_047_)
  );
  OR2_X1 _105_ (
    .A1(data_in[7]),
    .A2(data_out[7]),
    .ZN(_048_)
  );
  AND3_X1 _106_ (
    .A1(_023_),
    .A2(_047_),
    .A3(_048_),
    .ZN(_049_)
  );
  AND4_X1 _107_ (
    .A1(data_out[8]),
    .A2(_023_),
    .A3(_047_),
    .A4(_048_),
    .ZN(_050_)
  );
  NOR3_X1 _108_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(_022_),
    .ZN(_051_)
  );
  OR3_X1 _109_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(_022_),
    .ZN(_052_)
  );
  OAI21_X1 _110_ (
    .A(_052_),
    .B1(_049_),
    .B2(data_out[8]),
    .ZN(_053_)
  );
  NOR2_X1 _111_ (
    .A1(_050_),
    .A2(_053_),
    .ZN(_002_)
  );
  AND2_X1 _112_ (
    .A1(data_out[7]),
    .A2(_022_),
    .ZN(_054_)
  );
  AND2_X1 _113_ (
    .A1(_024_),
    .A2(_048_),
    .ZN(_055_)
  );
  XNOR2_X1 _114_ (
    .A(_046_),
    .B(_055_),
    .ZN(_056_)
  );
  OAI21_X1 _115_ (
    .A(_023_),
    .B1(_052_),
    .B2(data_in[7]),
    .ZN(_057_)
  );
  AOI21_X1 _116_ (
    .A(_057_),
    .B1(_056_),
    .B2(_052_),
    .ZN(_058_)
  );
  OR2_X1 _117_ (
    .A1(_054_),
    .A2(_058_),
    .ZN(_003_)
  );
  OAI21_X1 _118_ (
    .A(_026_),
    .B1(_027_),
    .B2(_044_),
    .ZN(_059_)
  );
  AOI21_X1 _119_ (
    .A(_051_),
    .B1(_059_),
    .B2(_045_),
    .ZN(_060_)
  );
  OAI21_X1 _120_ (
    .A(_023_),
    .B1(_052_),
    .B2(data_in[6]),
    .ZN(_061_)
  );
  NOR2_X1 _121_ (
    .A1(_060_),
    .A2(_061_),
    .ZN(_062_)
  );
  AOI21_X1 _122_ (
    .A(_062_),
    .B1(_022_),
    .B2(data_out[6]),
    .ZN(_063_)
  );
  INV_X1 _123_ (
    .A(_063_),
    .ZN(_004_)
  );
  XOR2_X1 _124_ (
    .A(data_in[5]),
    .B(data_out[5]),
    .Z(_064_)
  );
  XNOR2_X1 _125_ (
    .A(_043_),
    .B(_064_),
    .ZN(_065_)
  );
  MUX2_X1 _126_ (
    .A(data_in[5]),
    .B(_065_),
    .S(_052_),
    .Z(_066_)
  );
  MUX2_X1 _127_ (
    .A(data_out[5]),
    .B(_066_),
    .S(_023_),
    .Z(_005_)
  );
  NOR2_X1 _128_ (
    .A1(_042_),
    .A2(_051_),
    .ZN(_067_)
  );
  OAI21_X1 _129_ (
    .A(_067_),
    .B1(_041_),
    .B2(_028_),
    .ZN(_068_)
  );
  OAI21_X1 _130_ (
    .A(_068_),
    .B1(_052_),
    .B2(_021_),
    .ZN(_069_)
  );
  MUX2_X1 _131_ (
    .A(data_out[4]),
    .B(_069_),
    .S(_023_),
    .Z(_006_)
  );
  XOR2_X1 _132_ (
    .A(data_in[3]),
    .B(data_out[3]),
    .Z(_070_)
  );
  XNOR2_X1 _133_ (
    .A(_040_),
    .B(_070_),
    .ZN(_071_)
  );
  MUX2_X1 _134_ (
    .A(data_in[3]),
    .B(_071_),
    .S(_052_),
    .Z(_072_)
  );
  MUX2_X1 _135_ (
    .A(data_out[3]),
    .B(_072_),
    .S(_023_),
    .Z(_007_)
  );
  XNOR2_X1 _136_ (
    .A(_037_),
    .B(_039_),
    .ZN(_073_)
  );
  MUX2_X1 _137_ (
    .A(data_in[2]),
    .B(_073_),
    .S(_052_),
    .Z(_074_)
  );
  MUX2_X1 _138_ (
    .A(data_out[2]),
    .B(_074_),
    .S(_023_),
    .Z(_008_)
  );
  XNOR2_X1 _139_ (
    .A(_034_),
    .B(_036_),
    .ZN(_014_)
  );
  MUX2_X1 _140_ (
    .A(data_in[1]),
    .B(_014_),
    .S(_052_),
    .Z(_015_)
  );
  MUX2_X1 _141_ (
    .A(data_out[1]),
    .B(_015_),
    .S(_023_),
    .Z(_009_)
  );
  NAND2_X1 _142_ (
    .A1(data_out[0]),
    .A2(_052_),
    .ZN(_016_)
  );
  NAND2_X1 _143_ (
    .A1(data_in[0]),
    .A2(_023_),
    .ZN(_017_)
  );
  XOR2_X1 _144_ (
    .A(_016_),
    .B(_017_),
    .Z(_010_)
  );
  MUX2_X1 _145_ (
    .A(count[0]),
    .B(_085_[0]),
    .S(_023_),
    .Z(_011_)
  );
  NAND2_X1 _146_ (
    .A1(count[0]),
    .A2(_023_),
    .ZN(_018_)
  );
  XOR2_X1 _147_ (
    .A(count[1]),
    .B(_018_),
    .Z(_019_)
  );
  NOR2_X1 _148_ (
    .A1(end_cnt),
    .A2(_019_),
    .ZN(_012_)
  );
  OAI21_X1 _149_ (
    .A(_052_),
    .B1(_050_),
    .B2(data_out[9]),
    .ZN(_020_)
  );
  AOI21_X1 _150_ (
    .A(_020_),
    .B1(_050_),
    .B2(data_out[9]),
    .ZN(_013_)
  );
  INV_X1 _151_ (
    .A(data_in[4]),
    .ZN(_021_)
  );
  NOR2_X1 _152_ (
    .A1(_000_),
    .A2(valid_in),
    .ZN(_022_)
  );
  OR2_X1 _153_ (
    .A1(_000_),
    .A2(valid_in),
    .ZN(_023_)
  );
  NOR3_X1 _154_ (
    .A1(_085_[0]),
    .A2(_001_),
    .A3(_022_),
    .ZN(end_cnt)
  );
  NAND2_X1 _155_ (
    .A1(data_in[7]),
    .A2(data_out[7]),
    .ZN(_024_)
  );
  NAND2_X1 _156_ (
    .A1(data_in[6]),
    .A2(data_out[6]),
    .ZN(_025_)
  );
  XNOR2_X1 _157_ (
    .A(data_in[6]),
    .B(data_out[6]),
    .ZN(_026_)
  );
  NOR2_X1 _158_ (
    .A1(data_in[5]),
    .A2(data_out[5]),
    .ZN(_027_)
  );
  XOR2_X1 _159_ (
    .A(data_in[4]),
    .B(data_out[4]),
    .Z(_028_)
  );
  DFFR_X1 _160_ (
    .CK(clk),
    .D(_011_),
    .Q(count[0]),
    .QN(_085_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _161_ (
    .CK(clk),
    .D(_012_),
    .Q(count[1]),
    .QN(_001_),
    .RN(rst_n)
  );
  DFFR_X1 _162_ (
    .CK(clk),
    .D(_010_),
    .Q(data_out[0]),
    .QN(_075_),
    .RN(rst_n)
  );
  DFFR_X1 _163_ (
    .CK(clk),
    .D(_009_),
    .Q(data_out[1]),
    .QN(_076_),
    .RN(rst_n)
  );
  DFFR_X1 _164_ (
    .CK(clk),
    .D(_008_),
    .Q(data_out[2]),
    .QN(_077_),
    .RN(rst_n)
  );
  DFFR_X1 _165_ (
    .CK(clk),
    .D(_007_),
    .Q(data_out[3]),
    .QN(_078_),
    .RN(rst_n)
  );
  DFFR_X1 _166_ (
    .CK(clk),
    .D(_006_),
    .Q(data_out[4]),
    .QN(_079_),
    .RN(rst_n)
  );
  DFFR_X1 _167_ (
    .CK(clk),
    .D(_005_),
    .Q(data_out[5]),
    .QN(_080_),
    .RN(rst_n)
  );
  DFFR_X1 _168_ (
    .CK(clk),
    .D(_004_),
    .Q(data_out[6]),
    .QN(_081_),
    .RN(rst_n)
  );
  DFFR_X1 _169_ (
    .CK(clk),
    .D(_003_),
    .Q(data_out[7]),
    .QN(_082_),
    .RN(rst_n)
  );
  DFFR_X1 _170_ (
    .CK(clk),
    .D(_002_),
    .Q(data_out[8]),
    .QN(_083_),
    .RN(rst_n)
  );
  DFFR_X1 _171_ (
    .CK(clk),
    .D(_013_),
    .Q(data_out[9]),
    .QN(_084_),
    .RN(rst_n)
  );
  DFFR_X1 _172_ (
    .CK(clk),
    .D(end_cnt),
    .Q(valid_out),
    .QN(_000_),
    .RN(rst_n)
  );
  assign _085_[31:1] = { 30'h00000000, count[1] };
endmodule
