# rewritten for Synopsys tools by src/eval/sdc.py (time_scale=1)
# generated by src/eval/sdc.py  top=verified_accu lib=nangate45 period=0.1 ns  (config: constraints)
current_design verified_accu
create_clock -name clk -period 0.1 [get_ports clk]
set non_clk [snps_all_inputs_no_clocks]
set_input_delay 0.02 -clock clk $non_clk
set_output_delay 0.02 -clock clk [all_outputs]
set_driving_cell -lib_cell BUF_X1 $non_clk
set_max_fanout 20 [current_design]
