# generated by src/eval/sdc.py  top=verified_accu lib=sky130hd period=5 ns  (config: constraints)
current_design verified_accu
create_clock -name clk -period 5 [get_ports clk]
set non_clk [all_inputs -no_clocks]
set_input_delay 1 -clock clk $non_clk
set_output_delay 1 -clock clk [all_outputs]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_1 $non_clk
set_max_fanout 20 [current_design]
